#!/usr/bin/env python3
"""Audit the full-degree derivative-tower envelope and saturation table.

The proof document establishes two uniform statements:

1. the recursive block-projection row is exactly a prefix min-plus envelope;
2. a Chow decomposition must saturate every derivative degree through n-1.

The finite certificate is generated by a standard-library C++17 program.  It
uses an exact dual Ferrers dynamic program and verifies the saturation table
for n=3,...,10.  This Python driver compiles the source in a temporary
directory, validates the complete JSON output, binds the theorem-facing core,
and optionally writes the frozen payload.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import shutil
import subprocess
import tempfile
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
CPP_SOURCE = ROOT / "scripts" / "general_full_degree_tower_envelope.cpp"
EXPECTED_CORE_SHA256 = (
    "7532b223acc1cb28e6693d69a5e86153174470c674002ffc2fcf06a4470546d7"
)


def require(condition: bool, message: object) -> None:
    if not condition:
        raise RuntimeError(message)


def canonical_sha256(value: object) -> str:
    encoded = json.dumps(
        value,
        sort_keys=True,
        separators=(",", ":"),
    ).encode("utf-8")
    return hashlib.sha256(encoded).hexdigest()


def expected_thresholds() -> dict[str, list[int]]:
    return {
        "3": [3, 4],
        "4": [4, 7, 8],
        "5": [5, 11, 14, 15],
        "6": [6, 16, 24, 26, 27],
        "7": [7, 22, 39, 46, 48, 49],
        "8": [8, 29, 59, 80, 87, 89, 90],
        "9": [9, 37, 87, 136, 155, 161, 163, 164],
        "10": [10, 46, 123, 219, 280, 299, 305, 307, 307],
    }


def find_compiler() -> str:
    requested = os.environ.get("CXX")
    candidates = [requested] if requested else []
    candidates.extend(["g++", "c++", "clang++"])
    for candidate in candidates:
        if candidate and shutil.which(candidate):
            return candidate
    raise RuntimeError("No C++17 compiler found; exact replay fails closed")


def run_cpp_audit() -> dict[str, Any]:
    compiler = find_compiler()
    require(CPP_SOURCE.is_file(), CPP_SOURCE)
    with tempfile.TemporaryDirectory(prefix="perm_tower_cpp_") as directory:
        executable = Path(directory) / "general_full_degree_tower_envelope"
        compile_command = [
            compiler,
            "-std=c++17",
            "-O2",
            "-Wall",
            "-Wextra",
            "-pedantic",
            str(CPP_SOURCE),
            "-o",
            str(executable),
        ]
        subprocess.run(
            compile_command,
            check=True,
            capture_output=True,
            text=True,
            timeout=180,
        )
        completed = subprocess.run(
            [str(executable)],
            check=True,
            capture_output=True,
            text=True,
            timeout=300,
        )

    lines = [line for line in completed.stdout.splitlines() if line.strip()]
    require(len(lines) == 2, lines)
    require(lines[-1] == "GENERAL_FULL_DEGREE_TOWER_CPP_AUDIT_PASS", lines)
    payload = json.loads(lines[0])
    require(payload["thresholds"] == expected_thresholds(), payload)
    require(
        payload["boundary_capacities"]
        == {
            "7": {
                "degree": 6,
                "before_q": 48,
                "before": 44,
                "threshold_q": 49,
                "ambient": 49,
            },
            "8": {
                "degree": 7,
                "before_q": 89,
                "before": 60,
                "threshold_q": 90,
                "ambient": 64,
            },
            "9": {
                "degree": 8,
                "before_q": 163,
                "before": 74,
                "threshold_q": 164,
                "ambient": 81,
            },
            "10": {
                "degree": 8,
                "before_q": 306,
                "before": 2020,
                "threshold_q": 307,
                "ambient": 2025,
                "top_degree_before": 90,
                "top_degree_ambient": 100,
            },
        },
        payload,
    )
    return payload


def build_payload() -> dict[str, Any]:
    replay = run_cpp_audit()
    thresholds = replay["thresholds"]
    previous = {"7": 48, "8": 80, "9": 142, "10": 268}
    upper = {key: 2 ** (int(key) - 1) for key in previous}

    core: dict[str, Any] = {
        "status": [
            "GENERAL_FULL_DEGREE_TOWER_ENVELOPE_THEOREM",
            "EXACT_INTEGER_REPLAYED",
            "PERM7_LOWER_49",
            "PERM8_LOWER_90",
            "PERM9_LOWER_164",
            "PERM10_LOWER_307",
        ],
        "theorem": {
            "direct_cap": (
                "C_(n,d)(q)=min(M_(n,d)^2,q*M_(n,d),"
                "Gamma_(n,d)(B_(n,d-1)(q)))."
            ),
            "prefix_envelope": (
                "B_(n,d)(q)=q*M_(n,d)+min_(0<=t<=q)"
                "(C_(n,d)(t)-t*M_(n,d))."
            ),
            "saturation": (
                "Q_(n,d)=max(R_(n,d),ceil((M_(n,d)^2-P_(n,d))/"
                "M_(n,d))) with R=max(M,Q_(n,d-1)) and "
                "P=min_(0<=t<R)(C(t)-t*M)."
            ),
            "full_degree": (
                "The tower and saturation theorem apply through output "
                "degree n-1; output degree n has the same threshold as n-1."
            ),
            "rank_bound": (
                "ChowRank(perm_n)>=Theta_n=max_(1<=d<=n-1) Q_(n,d)."
            ),
        },
        "thresholds": {
            key: {
                "by_degree": values,
                "theta": max(values),
            }
            for key, values in thresholds.items()
        },
        "boundary_capacities": replay["boundary_capacities"],
        "new_bounds": {
            key: {
                "previous_accessible_lower_bound": previous[key],
                "tower_lower_bound": max(thresholds[key]),
                "glynn_upper_bound": upper[key],
            }
            for key in previous
        },
        "claim_boundary": (
            "The prefix-envelope and saturation formulas are uniform in n. "
            "The exact finite replay proves the stacked ordinary bounds "
            "perm_7>=49, perm_8>=90, perm_9>=164 and perm_10>=307. It does "
            "not prove exact rank for n>=6, a border-rank result, an "
            "asymptotic formula for Theta_n, or general Glynn optimality. "
            "The n=9 and n=10 rows are replayed by the standard-library C++ "
            "exact engine; the independent pure-Python reconstruction covers "
            "n<=8."
        ),
    }
    payload = {**core, "core_sha256": canonical_sha256(core)}
    require(payload["core_sha256"] == EXPECTED_CORE_SHA256, payload)
    return payload


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--json", type=Path)
    args = parser.parse_args()

    payload = build_payload()
    text = json.dumps(payload, indent=2, sort_keys=True) + "\n"
    if args.json:
        args.json.parent.mkdir(parents=True, exist_ok=True)
        args.json.write_text(text, encoding="utf-8", newline="\n")
    print(text, end="")
    print("GENERAL_FULL_DEGREE_TOWER_ENVELOPE_AUDIT_PASS")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
