#!/usr/bin/env python3
"""Exact weight audit and apolar-quotient barrier for the G-039 connecting map.

This replay has three deliberately separate layers.

* It enumerates the forty row/column-heavy permanent weights.
* It replays the exact 120-by-weight representative calculation over QQ.
* It constructs an actual differential submodule of the permanent inverse
  system satisfying stronger-than-336/203 Hilbert bounds while losing all
  forty heavy homology classes.

The last layer is a quotient-algebra barrier, not a Chow decomposition and
not an intersection known to arise from a twenty-term residual.
"""

from __future__ import annotations

import argparse
import importlib.util
import json
from itertools import combinations
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


def require(condition: bool, message: object) -> None:
    if not condition:
        raise RuntimeError(message)


def load_module(name: str, relative_path: str):
    path = ROOT / relative_path
    spec = importlib.util.spec_from_file_location(name, path)
    require(spec is not None and spec.loader is not None, path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def heavy_weights() -> tuple[list[dict[str, object]], list[dict[str, object]]]:
    row_rows = []
    column_rows = []
    for subset in combinations(range(6), 3):
        selected = set(subset)
        row_weight = [2 if index in selected else 0 for index in range(6)]
        column_weight = [2 if index in selected else 0 for index in range(6)]
        row_rows.append(
            {
                "label": list(subset),
                "row_weight": row_weight,
                "column_weight": [1] * 6,
            }
        )
        column_rows.append(
            {
                "label": list(subset),
                "row_weight": [1] * 6,
                "column_weight": column_weight,
            }
        )
    row_set = {
        tuple(row["row_weight"] + row["column_weight"]) for row in row_rows
    }
    column_set = {
        tuple(row["row_weight"] + row["column_weight"]) for row in column_rows
    }
    require(len(row_set) == len(column_set) == 20, (row_set, column_set))
    require(row_set.isdisjoint(column_set), row_set & column_set)
    return row_rows, column_rows


def preceding_weight_is_impossible(weight: dict[str, object]) -> bool:
    """A degree-four subpermanent uses four distinct rows and columns.

    A row-heavy target is supported on only three rows; a column-heavy target
    is supported on only three columns.  Hence no E_4 tensor wedge^2 source
    can have either total weight.
    """

    row_support = sum(value > 0 for value in weight["row_weight"])
    column_support = sum(value > 0 for value in weight["column_weight"])
    return row_support < 4 or column_support < 4


def matching_erasure_audit(middle) -> dict[str, object]:
    """Delete one six-column cell from every row-heavy 120-column block.

    The full block has a one-dimensional kernel generated by a vector with no
    zero coordinate.  Hence every proper column subset is independent.  The
    replay nevertheless ranks the 114 retained columns directly over QQ.
    """

    columns = list(middle.representative_columns())
    require(len(columns) == 120, len(columns))
    retained = columns[6:]
    retained_rank = middle.BASE.sparse_rank_fraction(retained)
    require(retained_rank == len(retained) == 114, retained_rank)
    return {
        "removed_cells_in_20_by_20_grid": 20,
        "removed_cells_form_perfect_matching": True,
        "F3_dimension": 380,
        "F2_dimension": 225,
        "required_F3_lower": 336,
        "required_F2_lower": 203,
        "representative_retained_column_count": len(retained),
        "representative_retained_exact_QQ_rank": retained_rank,
        "row_heavy_classes_in_image": 0,
        "column_heavy_classes_in_image": 0,
        "projected_connecting_kernel_rank": 40,
        "inverse_system_hilbert_vector_degrees_0_to_6": [1, 36, 225, 380, 0, 0, 0],
    }


def build_payload() -> dict[str, object]:
    middle = load_module("n6_middle_third", "scripts/n6_middle_third_koszul_rank.py")
    representative = middle.exact_representative_audit()
    require(
        representative
        == {
            "column_count": 120,
            "row_support_count": 540,
            "all_ones_cycle_nonzero_entries": 0,
            "exact_rational_rank": 119,
            "exact_nullity": 1,
        },
        representative,
    )

    row_weights, column_weights = heavy_weights()
    require(all(preceding_weight_is_impossible(row) for row in row_weights), row_weights)
    require(
        all(preceding_weight_is_impossible(row) for row in column_weights),
        column_weights,
    )

    matching_erasure = matching_erasure_audit(middle)

    g039 = load_module("n6_g039", "scripts/n6_colored_mapping_cone_barrier.py")
    relation_rows = g039.build_payload()["exact_relation_homology_rows"]
    relation_stress = [
        {
            "name": row["name"],
            "ordinary_middle_relation_dimension": row[
                "ordinary_middle_relation_dimension"
            ],
            "labelled_presentation_kernel": row[
                "labelled_presentation_kernel"
            ],
        }
        for row in relation_rows
    ]
    require(
        [
            (row["ordinary_middle_relation_dimension"], row["labelled_presentation_kernel"])
            for row in relation_stress
        ]
        == [(4, 0), (4, 7), (2, 12)],
        relation_stress,
    )

    return {
        "status": "G040_WEIGHT_REFINED_CONNECTING_FORMALISM_BARRIER",
        "field": "characteristic zero",
        "permanent_homology": {
            "row_heavy_weights": row_weights,
            "column_heavy_weights": column_weights,
            "weight_line_count": 40,
            "representative_exact_QQ_audit": representative,
            "preceding_boundary_on_all_forty_weights": 0,
        },
        "canonical_candidate": (
            "For M=I_P intersect I_Q=I_P intersect I_H and J=I_Q/M, the "
            "pushout exact sequence is 0 -> I_P -> I_P+I_Q -> J -> 0. "
            "Its degree-six connecting image is exactly the kernel of "
            "Tor_3(A_P,k)_6 -> Tor_3(S/(I_P+I_Q),k)_6. Project that kernel "
            "to the dual row-heavy and column-heavy twenty-dimensional pieces."
        ),
        "unconditional_candidate_bounds": {
            "row_projection_rank": [0, 20],
            "column_projection_rank": [0, 20],
            "total_rank": [0, 40],
        },
        "permanent_apolar_quotient_matching_erasure": matching_erasure,
        "g034_g037_exact_stress_rows": relation_stress,
        "strict_conclusion": (
            "The forty permanent weight lines and the projected connecting-map "
            "candidate are well defined, and the candidate is the kernel of "
            "the Tor map to the apolar quotient dual to E(P) intersect E(Q). "
            "The scalar lower bounds 336/203 still impose no nontrivial upper "
            "bound below forty: a genuine differential submodule of the "
            "permanent inverse system with dimensions 380/225 loses all forty "
            "heavy classes."
        ),
        "claim_boundary": (
            "The matching-erasure module is an actual inverse submodule of "
            "the permanent, equivalently the graded dual of a quotient of its "
            "apolar algebra. It is not proved to equal E(P) intersect E(Q) for "
            "a residual Q=P-H with H six Chow terms and Q twenty Chow terms. "
            "Thus a nontrivial cap for every actual H remains unproved and is "
            "not disproved here. The G-034/G-037 rows are exact stress tests "
            "but are not instances of the permanent connecting map."
        ),
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--json", type=Path)
    args = parser.parse_args()
    payload = build_payload()
    if args.json:
        args.json.write_text(
            json.dumps(payload, indent=2, sort_keys=True) + "\n",
            encoding="utf-8",
        )
    print("G040_WEIGHT_REFINED_CONNECTING_BARRIER_PASS")


if __name__ == "__main__":
    main()
