#!/usr/bin/env python3
"""Reconstruct and audit the 803 pending overlap-two multiminor rows."""

from __future__ import annotations

import argparse
import concurrent.futures
import json
import math
import multiprocessing
import os
from pathlib import Path
import sys
import time

import sympy as sp


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))
import n7_mixed_glynn_overlap_two_rank_one_shear_tail_rank as base  # noqa: E402


FAMILIES = ((2, 4), (2, 5), (3, 3), (4, 2))
EXPECTED_MULTI_MINOR_COUNTS = {(2, 4): 243, (2, 5): 71, (3, 3): 333, (4, 2): 156}
ROW_STATUS = "EXACT_LAURENT_UNIVARIATE_BEZOUT_EMPTY_TORUS_ZERO_SET"


def source_path(family):
    left_size, right_size = family
    return (
        ROOT
        / "data"
        / f"n7_mixed_glynn_overlap_two_{left_size}{right_size}_nilpotent_shear_tail_rank.json"
    )


def expected_candidate_count(left_size, right_size):
    support_count = (
        math.comb(6, 2)
        * math.comb(4, left_size - 2)
        * math.comb(6 - left_size, right_size - 2)
    )
    return support_count * 5


def reconstruct_minor(row, family, minor):
    left_size, right_size = family
    support = (
        tuple(row["core_support"]),
        tuple(row["left_extra_support"]),
        tuple(row["right_extra_support"]),
    )
    point = tuple(minor["selection_point"])
    weighted = bool(row.get("weighted_selection", False))
    witnesses = (
        base.weighted_witness_assignments(row["identity_count"], support, point)
        if weighted
        else base.witness_assignments(row["identity_count"], support, point)
    )
    if len(witnesses) != len(base.TAILS):
        raise AssertionError("saved selection point no longer has full modular rank")
    parameter_count = left_size + right_size - 2
    parameters = sp.symbols(f"p0:{parameter_count}")
    core, left_extra, right_extra = support
    matrix = sp.Matrix(
        [
            base.assignment_feature(
                assignment,
                row["identity_count"],
                core,
                left_extra,
                right_extra,
                parameters,
            )
            for assignment in witnesses
        ]
    ).T
    determinant = sp.Poly(
        matrix.det(method="domain-ge"), *parameters, domain=sp.ZZ
    )
    if determinant.total_degree() != minor["determinant_total_degree"]:
        raise AssertionError("determinant degree drift")
    if len(determinant.terms()) != minor["determinant_term_count"]:
        raise AssertionError("determinant term-count drift")
    return determinant


def laurent_univariate_reduction(determinant):
    terms = determinant.terms()
    parameter_count = len(determinant.gens)
    minima = tuple(
        min(exponents[index] for exponents, _coefficient in terms)
        for index in range(parameter_count)
    )
    z = sp.Symbol("z")
    residual = 0
    for exponents, coefficient in terms:
        shifted = tuple(
            exponent - minimum for exponent, minimum in zip(exponents, minima)
        )
        if shifted[0] != shifted[1] or any(shifted[2:]):
            raise AssertionError(
                "residual exponent lattice is not generated by (1,1,0,...)"
            )
        residual += coefficient * z**shifted[0]
    return minima, sp.Poly(residual, z, domain=sp.QQ).monic()


def audit_task(task):
    family, row = task
    if row["minor_count"] != 2:
        raise AssertionError("pending inventory must contain exactly two minors per row")
    reductions = []
    residual_gcd = None
    for minor in row["minors"]:
        determinant = reconstruct_minor(row, family, minor)
        monomial_exponents, residual = laurent_univariate_reduction(determinant)
        residual_gcd = (
            residual
            if residual_gcd is None
            else sp.gcd(residual_gcd, residual).monic()
        )
        reductions.append(
            {
                "selection_point": minor["selection_point"],
                "determinant_total_degree": determinant.total_degree(),
                "determinant_term_count": len(determinant.terms()),
                "torus_monomial_exponents": list(monomial_exponents),
                "residual_in_z_equals_p0_times_p1": str(residual.as_expr()),
            }
        )
    if residual_gcd is None or residual_gcd.degree() != 0:
        raise AssertionError(
            f"residual common root at {family}, {row['core_support']}, "
            f"split {row['identity_count']}: {residual_gcd}"
        )
    return {
        "family": list(family),
        "core_support": row["core_support"],
        "left_extra_support": row["left_extra_support"],
        "right_extra_support": row["right_extra_support"],
        "identity_count": row["identity_count"],
        "weighted_selection": bool(row.get("weighted_selection", False)),
        "minor_count": 2,
        "laurent_exponent_direction": [1, 1]
        + [0] * (family[0] + family[1] - 4),
        "reductions": reductions,
        "residual_gcd_over_Q_z": "1",
        "status": ROW_STATUS,
    }


def build_tasks():
    tasks = []
    source_inventory = []
    for family in FAMILIES:
        payload = json.loads(source_path(family).read_text(encoding="utf-8"))
        expected = expected_candidate_count(*family)
        if len(payload["rows"]) != expected:
            raise AssertionError(f"source candidate count drift for {family}")
        pending = [row for row in payload["rows"] if row["minor_count"] > 1]
        if len(pending) != EXPECTED_MULTI_MINOR_COUNTS[family]:
            raise AssertionError(f"source multiminor count drift for {family}")
        tasks.extend((family, row) for row in pending)
        source_inventory.append(
            {
                "family": list(family),
                "source_certificate": source_path(family).relative_to(ROOT).as_posix(),
                "source_candidate_count": expected,
                "multi_minor_row_count": len(pending),
            }
        )
    if len(tasks) != 803:
        raise AssertionError("pending lower-overlap inventory drift")
    return tasks, source_inventory


def build_payload(workers):
    tasks, source_inventory = build_tasks()
    if workers < 1 or workers > (os.cpu_count() or 1):
        raise ValueError("workers exceed visible CPUs")
    started = time.perf_counter()
    context = multiprocessing.get_context("fork") if os.name != "nt" else None
    with concurrent.futures.ProcessPoolExecutor(
        max_workers=workers, mp_context=context
    ) as pool:
        rows = list(pool.map(audit_task, tasks, chunksize=1))
    rows.sort(
        key=lambda row: (
            row["family"],
            row["core_support"],
            row["left_extra_support"],
            row["right_extra_support"],
            row["identity_count"],
        )
    )
    if {row["status"] for row in rows} != {ROW_STATUS}:
        raise AssertionError("incomplete torus-ideal audit")
    return {
        "schema_version": 1,
        "status": "EXACT_ALL_803_PENDING_OVERLAP_TWO_TORUS_IDEALS_AUDITED",
        "field": "characteristic zero",
        "candidate_formula": "243 + 71 + 333 + 156",
        "candidate_count": len(rows),
        "determinant_count": 2 * len(rows),
        "source_inventory": source_inventory,
        "workers": workers,
        "estimated_peak_memory_gib": 8.0,
        "elapsed_seconds": time.perf_counter() - started,
        "proof_method": (
            "Reconstruct both saved exact minors; remove each invertible "
            "coordinate monomial; verify that the residual exponent lattice "
            "is generated by (1,1,0,...); and compute gcd 1 in Q[z] for "
            "z=p0*p1."
        ),
        "rows": rows,
        "claim_boundary": [
            "This repairs the torus common-zero argument for all 803 formerly pending two-minor rows in families (2,4), (2,5), (3,3), and (4,2).",
            "It proves no non-nilpotent rank-one family, arbitrary GL(6), ordinary lower 50, exact rank 64, or border-rank statement.",
        ],
    }


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--workers", type=int, default=1)
    parser.add_argument("--json", type=Path)
    args = parser.parse_args()
    payload = build_payload(args.workers)
    text = json.dumps(payload, indent=2, sort_keys=True) + "\n"
    if args.json:
        args.json.write_text(text, encoding="utf-8")
    else:
        print(text, end="")


if __name__ == "__main__":
    main()
